#pragma once
#include "mouse_control.h"
#include "spells.h"

namespace Fire {
  struct Cast_Data {
    int spellIndex = 0;
    const char *name = "fireball";
  };


  int Fireball(entt::registry &zone, entt::entity &entity, float &x, float &y, const char *name) {
    //get data from db
    float castTime = 500.0f;

    //send to generic create
    zone.emplace_or_replace<Component::Casting>(entity, castTime, castTime, x, y, name);
    return 1;
  }

  Spells::spells Fire_Spells[] = {Fireball};

  int Cast_Spell(entt::registry &zone, entt::entity &entity, Action_Component::Action &action, int &index, float &x, float &y) {
    if (action.state != Action_Component::casting && action.state != Action_Component::cast) {

      //read animation in from db?
      Action_Component::Set_State(action, Action_Component::casting);
      Fire_Spells[0](zone, entity, x, y, "fireball");
    }
    return 0;
  }

  int Fire(entt::registry &zone, entt::entity &entity, Action_Component::Action &action, int &index, float &x, float &y) {
    if (action.state != Action_Component::casting && action.state != Action_Component::cast) {

      //read animation in from db?
      Action_Component::Set_State(action, Action_Component::casting);
      Fireball(zone, entity, x, y, "fire_1b_40");
    }
    return 0;
  }
}// namespace Fire

//
//Infernus_Altar1_1
//Infernus_Altar1_2
//Infernus_Altar1_3
//Infernus_Altar1_4
//Infernus_Altar3_1
//Infernus_Altar3_2
//Infernus_Altar3_3
//Infernus_Altar3_4
//Infernus_Altar_1
//Infernus_Altar_2
//Infernus_Altar_3
//Infernus_Altar_4
//Infernus_Altar_5
//Infernus_Altar_6
//Infernus_Altar_7
//Infernus_Altar_8
//Infernus_Bones1_1
//Infernus_Bones1_2
//Infernus_Bones1_3
//Infernus_Bones1_4
//Infernus_Bones1_5
//Infernus_Bones1_6
//Infernus_Bones1_7
//Infernus_Bones1_8
//Infernus_Book1_1
//Infernus_Book1_2
//Infernus_Book1_3
//Infernus_Book1_4
//Infernus_Book2_1
//Infernus_Book2_2
//Infernus_Book2_3
//Infernus_Book2_4
//Infernus_Bottle_1
//Infernus_Bottle_2
//Infernus_Bottle_3
//Infernus_Bottle_4
//Infernus_Bowl
//Infernus_Box1_1
//Infernus_Box1_2
//Infernus_Box1_3
//Infernus_Box1_4
//Infernus_Box2_1
//Infernus_Box2_2
//Infernus_Box2_3
//Infernus_Box2_4
//Infernus_Brasero
//Infernus_Burner
//Infernus_BurnerColumn_1
//Infernus_BurnerColumn_2
//Infernus_Bust1_1
//Infernus_Bust1_2
//Infernus_Bust1_3
//Infernus_Bust1_4
//Infernus_BustNiche_1
//Infernus_BustNiche_2
//Infernus_BustNiche_3
//Infernus_BustNiche_4
//Infernus_Cabinet1_1
//Infernus_Cabinet1_2
//Infernus_Cabinet1_3
//Infernus_Cabinet2_1
//Infernus_Cabinet2_2
//Infernus_Cabinet2_3
//Infernus_Cabinet3_1
//Infernus_Cabinet3_2
//Infernus_Cabinet3_3
//Infernus_Cage_1
//Infernus_Cage_2
//Infernus_Cage_3
//Infernus_Cage_4
//Infernus_CageCart_1
//Infernus_CageCart_2
//Infernus_CageCart_3
//Infernus_CageCart_4
//Infernus_Candelabra_1
//Infernus_Candelabra_2
//Infernus_Candelabra_3
//Infernus_Candelabra_4
//Infernus_Candles_1
//Infernus_Candles_2
//Infernus_Candles_3
//Infernus_Candles_4
//Infernus_Candles_5
//Infernus_Candles_6
//Infernus_Candles_7
//Infernus_Chalice
//Infernus_Club_1
//Infernus_Club_2
//Infernus_Club_3
//Infernus_Club_4
//Infernus_Club_5
//Infernus_Club_6
//Infernus_Club_7
//Infernus_Club_8
//Infernus_Column
//Infernus_Corpse1_1
//Infernus_Corpse1_2
//Infernus_Corpse1_3
//Infernus_Corpse1_4
//Infernus_Corpse1_5
//Infernus_Corpse1_6
//Infernus_Corpse1_7
//Infernus_Corpse1_8
//Infernus_Crater
//Infernus_Cup
//Infernus_Decal
//Infernus_Decor1_1
//Infernus_Decor1_2
//Infernus_Decor1_3
//Infernus_Decor1_4
//Infernus_Decor2_1
//Infernus_Decor2_2
//Infernus_Decor2_3
//Infernus_Decor2_4
//Infernus_Decor3_1
//Infernus_Decor3_2
//Infernus_DragonBones1_1
//Infernus_DragonBones1_2
//Infernus_DragonBones1_3
//Infernus_DragonBones1_4
//Infernus_DragonBones1_5
//Infernus_DragonBones1_6
//Infernus_DragonBones1_7
//Infernus_DragonBones1_8
//Infernus_DragonBones2_1
//Infernus_DragonBones2_2
//Infernus_DragonBones2_3
//Infernus_DragonBones2_4
//Infernus_DragonBones2_5
//Infernus_DragonBones2_6
//Infernus_DragonBones2_7
//Infernus_DragonBones2_8
//Infernus_FloatingIsle_1
//Infernus_FloatingIsle_2
//Infernus_FloatingIsle_3
//Infernus_FloatingIsle_4
//Infernus_FloatingIsle_5
//Infernus_FloorDecal
//Infernus_GorePile_1
//Infernus_GorePile_2
//Infernus_GorePile_3
//Infernus_GorePile_4
//Infernus_GorePile_5
//Infernus_GorePile_6
//Infernus_GorePile_7
//Infernus_GorePile_8
//Infernus_Grave1_1
//Infernus_Grave1_2
//Infernus_Grave1_3
//Infernus_Grave1_4
//Infernus_Grave1_5
//Infernus_Grave1_6
//Infernus_Grave1_7
//Infernus_Grave1_8
//Infernus_Grave3_1
//Infernus_Grave3_2
//Infernus_Grave3_3
//Infernus_Grave3_4
//Infernus_Grave3_5
//Infernus_Grave3_6
//Infernus_Ground
//Infernus_HangingCorpse1_0
//Infernus_HangingCorpse1_1
//Infernus_HangingCorpse1_2
//Infernus_HangingCorpse1_3
//Infernus_HangingCorpse1_4
//Infernus_HangingCorpse2_1
//Infernus_HangingCorpse2_2
//Infernus_HangingCorpse2_3
//Infernus_HangingCorpse2_4
//Infernus_Hellscape_BrokenGiant_1
//Infernus_Hellscape_BrokenGiant_2
//Infernus_Hellscape_BrokenGiant_3
//Infernus_Hellscape_BrokenGiant_4
//Infernus_Hellscape_BrokenGiant_5
//Infernus_Hellscape_BrokenGiant_6
//Infernus_Hellscape_BrokenGiant_7
//Infernus_Hellscape_BrokenGiant_8
//Infernus_Hellscape_BrokenHand1_1
//Infernus_Hellscape_BrokenHand1_2
//Infernus_Hellscape_BrokenHand1_3
//Infernus_Hellscape_BrokenHand1_4
//Infernus_Hellscape_BrokenHand1_5
//Infernus_Hellscape_BrokenHand1_6
//Infernus_Hellscape_BrokenHand1_7
//Infernus_Hellscape_BrokenHand1_8
//Infernus_Hellscape_BrokenHand2_1
//Infernus_Hellscape_BrokenHand2_2
//Infernus_Hellscape_BrokenHand2_3
//Infernus_Hellscape_BrokenHand2_4
//Infernus_Hellscape_BrokenHand2_5
//Infernus_Hellscape_BrokenHand2_6
//Infernus_Hellscape_BrokenHand2_7
//Infernus_Hellscape_BrokenHand2_8
//Infernus_Hellscape_BrokenHead2_1
//Infernus_Hellscape_BrokenHead2_2
//Infernus_Hellscape_BrokenHead2_3
//Infernus_Hellscape_BrokenHead2_4
//Infernus_Hellscape_BrokenHead2_5
//Infernus_Hellscape_BrokenHead2_6
//Infernus_Hellscape_BrokenHead2_7
//Infernus_Hellscape_BrokenHead2_8
//Infernus_Hellscape_BrokenHead_1
//Infernus_Hellscape_BrokenHead_2
//Infernus_Hellscape_BrokenHead_3
//Infernus_Hellscape_BrokenHead_4
//Infernus_Hellscape_BrokenHead_5
//Infernus_Hellscape_BrokenHead_6
//Infernus_Hellscape_BrokenHead_7
//Infernus_Hellscape_BrokenHead_8
//Infernus_Hellscape_Cliff1_1
//Infernus_Hellscape_Cliff1_2
//Infernus_Hellscape_Cliff1_3
//Infernus_Hellscape_Cliff1_4
//Infernus_Hellscape_Cliff1_5
//Infernus_Hellscape_Cliff1_6
//Infernus_Hellscape_Cliff1_7
//Infernus_Hellscape_Cliff1_8
//Infernus_Hellscape_Cliff2_1
//Infernus_Hellscape_Cliff2_2
//Infernus_Hellscape_Cliff2_3
//Infernus_Hellscape_Cliff3_1
//Infernus_Hellscape_Cliff3_2
//Infernus_Hellscape_Cliff3_3
//Infernus_Hellscape_Columns_1
//Infernus_Hellscape_Columns_2
//Infernus_Hellscape_Columns_3
//Infernus_Hellscape_Columns_4
//Infernus_Hellscape_Ground_1
//Infernus_Hellscape_Ground_2
//Infernus_Hellscape_Ground_3
//Infernus_Hellscape_Ground_4
//Infernus_Hellscape_Pile1_1
//Infernus_Hellscape_Pile1_2
//Infernus_Hellscape_Pile1_3
//Infernus_Hellscape_Pile1_4
//Infernus_Hellscape_Pile1_5
//Infernus_Hellscape_Pile1_6
//Infernus_Hellscape_Pile1_7
//Infernus_Hellscape_Pile1_8
//Infernus_Hellscape_Pile2_1
//Infernus_Hellscape_Pile2_2
//Infernus_Hellscape_Pile2_3
//Infernus_Hellscape_Pile2_4
//Infernus_Hellscape_Pile2_5
//Infernus_Hellscape_Pile2_6
//Infernus_Hellscape_Pile2_7
//Infernus_Hellscape_Pile2_8
//Infernus_Hellscape_Pile3_1
//Infernus_Hellscape_Platform_1
//Infernus_Hellscape_Platform_2
//Infernus_Hellscape_Platform_3
//Infernus_Hellscape_Platform_4
//Infernus_Hellscape_Rock_1
//Infernus_Hellscape_Rock_2
//Infernus_Hellscape_Rock_3
//Infernus_Hellscape_Rock_4
//Infernus_Hellscape_Rock_5
//Infernus_Hellscape_Rock_6
//Infernus_Hellscape_Rock_7
//Infernus_Hellscape_Rocks_1
//Infernus_Hellscape_Rocks_2
//Infernus_Hellscape_Rocks_3
//Infernus_Hellscape_Rocks_4
//Infernus_Hellscape_Rocks_5
//Infernus_Hellscape_Rocks_6
//Infernus_Hellscape_Rubble1_1
//Infernus_Hellscape_Rubble1_2
//Infernus_Hellscape_Rubble1_3
//Infernus_Hellscape_Rubble1_4
//Infernus_Hellscape_Rubble1_5
//Infernus_Hellscape_Rubble1_6
//Infernus_Hellscape_Rubble1_7
//Infernus_Hellscape_Rubble1_8
//Infernus_Hellscape_Rubble1_9
//Infernus_Hellscape_Rubble1_10
//Infernus_Hellscape_Rubble1_11
//Infernus_Hellscape_Rubble1_12
//Infernus_Hellscape_Rubble1_13
//Infernus_Hellscape_Rubble1_14
//Infernus_Hellscape_Rubble1_15
//Infernus_Hellscape_Rubble2_1
//Infernus_Hellscape_Rubble2_2
//Infernus_Hellscape_Rubble2_3
//Infernus_Hellscape_Rubble2_4
//Infernus_Hellscape_Rubble2_5
//Infernus_Hellscape_Rubble2_6
//Infernus_Hellscape_Rubble2_7
//Infernus_Hellscape_Rubble2_8
//Infernus_Hellscape_Rubble3_1
//Infernus_Hellscape_Rubble3_2
//Infernus_Hellscape_Rubble3_3
//Infernus_Hellscape_Rubble3_4
//Infernus_Hellscape_Rubble3_5
//Infernus_Hellscape_Rubble3_6
//Infernus_Hellscape_Rubble3_7
//Infernus_Hellscape_Rubble3_8
//Infernus_Hellscape_Rubble4_1
//Infernus_Hellscape_Rubble4_2
//Infernus_Hellscape_Rubble4_3
//Infernus_Hellscape_Rubble4_4
//Infernus_Hellscape_Rubble4_5
//Infernus_Hellscape_Rubble4_6
//Infernus_Hellscape_Rubble4_7
//Infernus_Hellscape_Rubble4_8
//Infernus_Hellscape_Rubble5_1
//Infernus_Hellscape_Rubble5_2
//Infernus_Hellscape_Rubble5_3
//Infernus_Hellscape_Rubble5_4
//Infernus_Hellscape_Rubble5_5
//Infernus_Hellscape_Rubble5_6
//Infernus_Hellscape_Rubble5_7
//Infernus_Hellscape_Rubble5_8
//Infernus_Hellscape_StoneSpire_1
//Infernus_Hellscape_StoneSpire_2
//Infernus_Hellscape_StoneSpire_3
//Infernus_Hellscape_StoneSpire_4
//Infernus_Jar
//Infernus_Lectern1_1
//Infernus_Lectern1_2
//Infernus_Lectern1_3
//Infernus_Lectern1_4
//Infernus_Lectern1_5
//Infernus_Lectern1_6
//Infernus_Lectern1_7
//Infernus_Lectern1_8
//Infernus_PentagramFloor
//Infernus_PentagramWall_1
//Infernus_PentagramWall_2
//Infernus_PentagramWall_3
//Infernus_Pillar_1
//Infernus_Pillar_2
//Infernus_Reliquary_1
//Infernus_Reliquary_2
//Infernus_RitualKryss_1
//Infernus_RitualKryss_2
//Infernus_RitualKryss_3
//Infernus_RitualKryss_4
//Infernus_RitualKryss_5
//Infernus_RitualKryss_6
//Infernus_RitualKryss_7
//Infernus_RitualKryss_8
//Infernus_SacrificialChalice
//Infernus_SacrificialDagger_1
//Infernus_SacrificialDagger_2
//Infernus_SacrificialDagger_3
//Infernus_SacrificialDagger_4
//Infernus_SacrificialDagger_5
//Infernus_SacrificialDagger_6
//Infernus_SacrificialDagger_7
//Infernus_SacrificialDagger_8
//Infernus_Shelf_1
//Infernus_Shelf_2
//Infernus_Shelf_3
//Infernus_Shelf_4
//Infernus_Shield
//Infernus_Skull1_1
//Infernus_Skull1_2
//Infernus_Skull1_3
//Infernus_Skull1_4
//Infernus_Skull2_1
//Infernus_Skull2_2
//Infernus_Skull2_3
//Infernus_Skull2_4
//Infernus_Skull3_1
//Infernus_Skull3_2
//Infernus_Skull3_3
//Infernus_Skull3_4
//Infernus_Skull4_1
//Infernus_Skull4_2
//Infernus_Skull4_3
//Infernus_Skull4_4
//Infernus_Skull5_1
//Infernus_Skull5_2
//Infernus_Skull5_3
//Infernus_Skull5_4
//Infernus_Spear_1
//Infernus_Spear_2
//Infernus_Spear_3
//Infernus_Spear_4
//Infernus_Spear_5
//Infernus_Spear_6
//Infernus_Spear_7
//Infernus_Spear_8
//Infernus_Staff_1
//Infernus_Staff_2
//Infernus_Staff_3
//Infernus_Staff_4
//Infernus_Stand_1
//Infernus_Stand_2
//Infernus_Stand_3
//Infernus_Stand_4
//Infernus_Stand_5
//Infernus_Stand_6
//Infernus_Stand_7
//Infernus_Stand_8
//Infernus_Sword_1
//Infernus_Sword_2
//Infernus_Sword_3
//Infernus_Sword_4
//Infernus_Sword_5
//Infernus_Sword_6
//Infernus_Sword_7
//Infernus_Sword_8
//Infernus_Table_1
//Infernus_Table_2
//Infernus_Throne_1
//Infernus_Throne_2
//Infernus_Throne_3
//Infernus_Throne_4
//Infernus_Throne_5
//Infernus_Throne_6
//Infernus_Throne_7
//Infernus_Throne_8
//Infernus_Vase
//Infernus_WallCandles_1
//Infernus_WallCandles_2
//Infernus_WallCandles_3
//Infernus_WallCandles_4
//Infernus_WallCandles_5
//Infernus_WallClub
//Infernus_WallLantern_1
//Infernus_WallLantern_2
//Infernus_WallLantern_3
//Infernus_WallLantern_4
//Infernus_WallLantern_5
//Infernus_WallRitualKryss_1
//Infernus_WallRitualKryss_2
//Infernus_WallRitualKryss_3
//Infernus_WallShield_1
//Infernus_WallShield_2
//Infernus_WallShield_3
//Infernus_WallSpear_1
//Infernus_WallSpear_2
//Infernus_WallSpear_3
//Infernus_WallSword_1
//Infernus_WallSword_2
//Infernus_WallSword_3