#include "Necromancy/raise_skeleton.h"
#include "Necromancy/summon_demon.h"
#include "Necromancy/reanimate.h"
#include "Necromancy/arrogate_ghost.h"
#include "Necromancy/raise_zombie.h"
#include "Necromancy/metamorphosis.h"